### PR TITLE
Log updated images to json file

### PR DESCRIPTION
**Pull request by upupming**
Hi, this PR is as per #13, I have decided to use a global json file to log all uploaded images.

### Screenshot

image

### Details

1. The plugin will create a file named `vs-picgo-log.json` under user home directory, user can customize this directory as well.
2. If any error found in the json file when updating it, the plugin will make useful suggestions.

### Update

See comments below for update.

### CODE REVIEW

**Comment by Molunerfinn** [comment]
I suggest you can use the same configuration format as PicGo.

For example:

```json
"uploaded": {
      "extname": ".jpg",
      "fileName": "xxx.jpg",
      "height": 514,
      "imgUrl": "http://xxx.com/xxx.jpg",
      "type": "tcyun",
      "width": 514,
      "id": "0011539b-be3e-4e6d-8360-86944f3a10e9"
    },
    // ...
}
```

**Comment by upupming** [comment]
Sure, thanks for that information! I have just dive in PicGo dev so maybe I
am not so familiar all is configuration.

**Comment by upupming** [comment]
Just to make sure I'm going the right way:

I don't have other picBed so I'm testing on sm.ms, there will be no `id` filed:

image

The only docs about `id` field is [here](https://picgo.github.io/PicGo-Core-Doc/zh/dev-guide/gui.html#remove)

**Comment by Molunerfinn** [comment]
@upupming `id` is generated by you, not by `picgo-core`, it's for PicGo's gallery to find the specific image as long as the `id` is not repeated.

**Comment by Molunerfinn** [comment]
PicGo uses [lodash-id](https://github.com/typicode/lodash-id) to generate `id`.

**Comment by upupming** [comment]
Thanks, I think we can add this to the `PicGo-Core` doc, too.

**Comment by Molunerfinn** [comment]
> So PicGo needs this but PicGo-Core doesn't need this. `vs-picgo` should do as `PicGo`!

Yes. If you want to do migrate after this feature, you should generate the `id` field by now. 

`PicGo-Core` is the core-part for pictures uploading, so any other features will be supported by plugins.

**Comment by upupming** [comment]
Finished as suggested by @Molunerfinn (big thanks to you sir), this is a screenshot:

image

### demo

vs-picgo-log

**Comment by Molunerfinn** [comment]
image
this should be `uploaded` not `smms` haha.

**Comment by Molunerfinn** [comment]
The following is the origin PicGo's data file:
image
image

**Comment by upupming** [comment]
Sure, I just use different keys for different picBed, in this way we can
index all images on one picBed more efficiently. Shall we change back to
`uploaded` for all picBeds?

**Comment by Molunerfinn** [comment]
I think logs should focus more on chronological order than type

**Comment by Molunerfinn** [comment]
Well it's not my repo, so you should ask @Spades-S for advices~

**Comment by upupming** [comment]
Based on https://github.com/Spades-S/vs-picgo/pull/14#issuecomment-478578969, I have implemented https://github.com/upupming/picgo-plugin-vscode-migrator, hope it will be helpful.

**Comment by Spades-S** [comment]
> I think logs should focus more on chronological order than type

@upupming @Molunerfinn  Yeah, i agree with @Molunerfinn, for the log file, chronological order should be more focused. And we can rearrange the items by  item.type

**Comment by upupming** [comment]
@Spades-S @Molunerfinn Thanks for both of your advice. Now I have changed to use `uploaded` key only, this will keep picgo and vs-picgo logs consistent.

**Pull request merged**
